openapi: "3.0.3"
info:
  title: "TimeLine API"
  description: "TimeLine API"
  version: "1.0.0"
servers:
- url: "https://TimeLine"
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Welcome to server."
  /wechat/auth/{code}:
    get:
      description: ""
      parameters:
      - name: "code"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CodeSession"
components:
  schemas:
    CodeSession:
      type: "object"
      properties:
        sessionKey:
          type: "string"
        unionId:
          type: "string"
        errorMessage:
          type: "string"
        openId:
          type: "string"
        errorCode:
          type: "integer"
          format: "int32"