/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            'text/plain': string
          }
        }
      }
    }
  }
  '/wechat/auth/{code}': {
    get: {
      parameters: {
        path: {
          code: string
        }
      }
      responses: {
        /** @description OK */
        200: {
          content: {
            '*/*': components['schemas']['CodeSession']
          }
        }
      }
    }
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    CodeSession: {
      sessionKey: string
      unionId: string
      errorMessage: string
      openId: string
      /** Format: int32 */
      errorCode?: number
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export type operations = Record<string, never>
