package ui

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

fun TimeLineColorLightTokens(
    primary: Color = Color(0xFF644BB9),
    onPrimary: Color = Color(0xFFFFFFFF),
    primaryContainer: Color = Color(0xFFE7DEFF),
    onPrimaryContainer: Color = Color(0xFF1F0060),
    secondary: Color = Color(0xFF4F56A9),
    onSecondary: Color = Color(0xFFFFFFFF),
    secondaryContainer: Color = Color(0xFFE0E0FF),
    onSecondaryContainer: Color = Color(0xFF040865),
    tertiary: Color = Color(0xFF5056A9),
    onTertiary: Color = Color(0xFFFFFFFF),
    tertiaryContainer: Color = Color(0xFFE0E0FF),
    onTertiaryContainer: Color = Color(0xFF050865),
    error: Color = Color(0xFFBA1A1A),
    errorContainer: Color = Color(0xFFFFDAD6),
    onError: Color = Color(0xFFFFFFFF),
    onErrorContainer: Color = Color(0xFF410002),
    background: Color = Color(0xFFFFFBFF),
    onBackground: Color = Color(0xFF1C1B1E),
    surface: Color = Color(0xFFFFFBFF),
    onSurface: Color = Color(0xFF1C1B1E),
    surfaceVariant: Color = Color(0xFFE6E0EC),
    onSurfaceVariant: Color = Color(0xFF48454E),
    outline: Color = Color(0xFF79757F),
    inverseOnSurface: Color = Color(0xFFF4EFF4),
    inverseSurface: Color = Color(0xFF313033),
    inversePrimary: Color = Color(0xFFCCBDFF),
    shadow: Color = Color(0xFF000000),
    surfaceTint: Color = Color(0xFF644BB9),
    outlineVariant: Color = Color(0xFFCAC4CF),
    scrim: Color = Color(0xFF000000)
) =
    ColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        inversePrimary = inversePrimary,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        surfaceTint = surfaceTint,
        inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface,
        error = error,
        onError = onError,
        errorContainer = errorContainer,
        onErrorContainer = onErrorContainer,
        outline = outline,
        outlineVariant = outlineVariant,
        scrim = scrim,
        surfaceBright = surface,
        surfaceContainer = secondaryContainer,
        surfaceContainerHigh = secondaryContainer,
        surfaceContainerHighest = surface,
        surfaceContainerLow = surface,
        surfaceContainerLowest = surface,
        surfaceDim = surfaceVariant,
    )


fun TimeLineColorDarkTokens(
     primary: Color =Color(0xFFCCBDFF),
     onPrimary: Color =Color(0xFF351289),
     primaryContainer: Color =Color(0xFF4C31A0),
     onPrimaryContainer: Color =Color(0xFFE7DEFF),
     secondary: Color =Color(0xFFBEC2FF),
     onSecondary: Color =Color(0xFF1F2578),
     secondaryContainer: Color =Color(0xFF373E90),
     onSecondaryContainer: Color =Color(0xFFE0E0FF),
     tertiary: Color =Color(0xFFBFC2FF),
     onTertiary: Color =Color(0xFF202578),
     tertiaryContainer: Color =Color(0xFF383E8F),
     onTertiaryContainer: Color =Color(0xFFE0E0FF),
     error: Color =Color(0xFFFFB4AB),
     errorContainer: Color =Color(0xFF93000A),
     onError: Color =Color(0xFF690005),
     onErrorContainer: Color =Color(0xFFFFDAD6),
     background: Color =Color(0xFF1C1B1E),
     onBackground: Color =Color(0xFFE6E1E6),
     surface: Color =Color(0xFF1C1B1E),
     onSurface: Color =Color(0xFFE6E1E6),
     surfaceVariant: Color =Color(0xFF48454E),
     onSurfaceVariant: Color =Color(0xFFCAC4CF),
     outline: Color =Color(0xFF938F99),
     inverseOnSurface: Color =Color(0xFF1C1B1E),
     inverseSurface: Color =Color(0xFFE6E1E6),
     inversePrimary: Color =Color(0xFF644BB9),
     shadow: Color =Color(0xFF000000),
     surfaceTint: Color =Color(0xFFCCBDFF),
     outlineVariant: Color =Color(0xFF48454E),
     scrim: Color =Color(0xFF000000)
) =
    ColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        inversePrimary = inversePrimary,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        surfaceTint = surfaceTint,
        inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface,
        error = error,
        onError = onError,
        errorContainer = errorContainer,
        onErrorContainer = onErrorContainer,
        outline = outline,
        outlineVariant = outlineVariant,
        scrim = scrim,
        surfaceBright = surface,
        surfaceContainer = secondaryContainer,
        surfaceContainerHigh = secondaryContainer,
        surfaceContainerHighest = surface,
        surfaceContainerLow = surface,
        surfaceContainerLowest = surface,
        surfaceDim = surfaceVariant,
    )

