package ui

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color


fun TimeLineColorLightThreeTokens(

    primary:Color = Color(0xFF7A5900),
    onPrimary:Color = Color(0xFFFFFFFF),
    primaryContainer:Color = Color(0xFFFFDEA2),
    onPrimaryContainer:Color = Color(0xFF261900),
    secondary:Color = Color(0xFF6C5C3F),
    onSecondary:Color = Color(0xFFFFFFFF),
    secondaryContainer:Color = Color(0xFFF6E0BB),
    onSecondaryContainer:Color = Color(0xFF251A04),
    tertiary:Color = Color(0xFF4B6546),
    onTertiary:Color = Color(0xFFFFFFFF),
    tertiaryContainer:Color = Color(0xFFCDEBC3),
    onTertiaryContainer:Color = Color(0xFF092008),
    error:Color = Color(0xFFBA1A1A),
    errorContainer:Color = Color(0xFFFFDAD6),
    onError:Color = Color(0xFFFFFFFF),
    onErrorContainer:Color = Color(0xFF410002),
    background:Color = Color(0xFFFFFBFF),
    onBackground:Color = Color(0xFF1E1B16),
    surface:Color = Color(0xFFFFFBFF),
    onSurface:Color = Color(0xFF1E1B16),
    surfaceVariant:Color = Color(0xFFEDE1CF),
    onSurfaceVariant:Color = Color(0xFF4D4639),
    outline:Color = Color(0xFF7F7667),
    inverseOnSurface:Color = Color(0xFFF8EFE7),
    inverseSurface:Color = Color(0xFF34302A),
    inversePrimary:Color = Color(0xFFF4BE48),
    shadow:Color = Color(0xFF000000),
    surfaceTint:Color = Color(0xFF7A5900),
    outlineVariant:Color = Color(0xFFD1C5B4),
    scrim:Color = Color(0xFF000000),
) =
    ColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        inversePrimary = inversePrimary,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        surfaceTint = surfaceTint,
        inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface,
        error = error,
        onError = onError,
        errorContainer = errorContainer,
        onErrorContainer = onErrorContainer,
        outline = outline,
        outlineVariant = outlineVariant,
        scrim = scrim,
        surfaceBright = surface,
        surfaceContainer = secondaryContainer,
        surfaceContainerHigh = secondaryContainer,
        surfaceContainerHighest = surface,
        surfaceContainerLow = surface,
        surfaceContainerLowest = surface,
        surfaceDim = surfaceVariant,
    )


fun TimeLineColorDarkThreeTokens(
    primary:Color = Color(0xFFF4BE48),
    onPrimary:Color = Color(0xFF402D00),
    primaryContainer:Color = Color(0xFF5C4200),
    onPrimaryContainer:Color = Color(0xFFFFDEA2),
    secondary:Color = Color(0xFFD9C4A0),
    onSecondary:Color = Color(0xFF3B2F15),
    secondaryContainer:Color = Color(0xFF53452A),
    onSecondaryContainer:Color = Color(0xFFF6E0BB),
    tertiary:Color = Color(0xFFB1CFA8),
    onTertiary:Color = Color(0xFF1E361B),
    tertiaryContainer:Color = Color(0xFF344D30),
    onTertiaryContainer:Color = Color(0xFFCDEBC3),
    error:Color = Color(0xFFFFB4AB),
    errorContainer:Color = Color(0xFF93000A),
    onError:Color = Color(0xFF690005),
    onErrorContainer:Color = Color(0xFFFFDAD6),
    background:Color = Color(0xFF1E1B16),
    onBackground:Color = Color(0xFFE9E1D9),
    surface:Color = Color(0xFF1E1B16),
    onSurface:Color = Color(0xFFE9E1D9),
    surfaceVariant:Color = Color(0xFF4D4639),
    onSurfaceVariant:Color = Color(0xFFD1C5B4),
    outline:Color = Color(0xFF998F80),
    inverseOnSurface:Color = Color(0xFF1E1B16),
    inverseSurface:Color = Color(0xFFE9E1D9),
    inversePrimary:Color = Color(0xFF7A5900),
    shadow:Color = Color(0xFF000000),
    surfaceTint:Color = Color(0xFFF4BE48),
    outlineVariant:Color = Color(0xFF4D4639),
    scrim:Color = Color(0xFF000000),
) =
    ColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        inversePrimary = inversePrimary,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        surfaceTint = surfaceTint,
        inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface,
        error = error,
        onError = onError,
        errorContainer = errorContainer,
        onErrorContainer = onErrorContainer,
        outline = outline,
        outlineVariant = outlineVariant,
        scrim = scrim,
        surfaceBright = surface,
        surfaceContainer = secondaryContainer,
        surfaceContainerHigh = secondaryContainer,
        surfaceContainerHighest = surface,
        surfaceContainerLow = surface,
        surfaceContainerLowest = surface,
        surfaceDim = surfaceVariant,
    )




