package ui

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color


fun TimeLineColorLightTwoTokens(
    primary:Color= Color(0xFFBF0026),
    onPrimary:Color= Color(0xFFFFFFFF),
    primaryContainer:Color= Color(0xFFFFDAD8),
    onPrimaryContainer:Color= Color(0xFF410006),
    secondary:Color= Color(0xFF775655),
    onSecondary:Color= Color(0xFFFFFFFF),
    secondaryContainer:Color= Color(0xFFFFDAD8),
    onSecondaryContainer:Color= Color(0xFF2C1514),
    tertiary:Color= Color(0xFF745A2E),
    onTertiary:Color= Color(0xFFFFFFFF),
    tertiaryContainer:Color= Color(0xFFFFDEAB),
    onTertiaryContainer:Color= Color(0xFF271900),
    error:Color= Color(0xFFBA1A1A),
    errorContainer:Color= Color(0xFFFFDAD6),
    onError:Color= Color(0xFFFFFFFF),
    onErrorContainer:Color= Color(0xFF410002),
    background:Color= Color(0xFFFFFBFF),
    onBackground:Color= Color(0xFF201A1A),
    surface:Color= Color(0xFFFFFBFF),
    onSurface:Color= Color(0xFF201A1A),
    surfaceVariant:Color= Color(0xFFF4DDDC),
    onSurfaceVariant:Color= Color(0xFF524342),
    outline:Color= Color(0xFF857372),
    inverseOnSurface:Color= Color(0xFFFBEEED),
    inverseSurface:Color= Color(0xFF362F2E),
    inversePrimary:Color= Color(0xFFFFB3B0),
    shadow:Color= Color(0xFF000000),
    surfaceTint:Color= Color(0xFFBF0026),
    outlineVariant:Color= Color(0xFFD7C1C0),
    scrim:Color= Color(0xFF000000)

) =
    ColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        inversePrimary = inversePrimary,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        surfaceTint = surfaceTint,
        inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface,
        error = error,
        onError = onError,
        errorContainer = errorContainer,
        onErrorContainer = onErrorContainer,
        outline = outline,
        outlineVariant = outlineVariant,
        scrim = scrim,
        surfaceBright = surface,
        surfaceContainer = secondaryContainer,
        surfaceContainerHigh = secondaryContainer,
        surfaceContainerHighest = surface,
        surfaceContainerLow = surface,
        surfaceContainerLowest = surface,
        surfaceDim = surfaceVariant,
    )


fun TimeLineColorDarkTwoTokens(
    primary:Color= Color(0xFFFFB3B0),
    onPrimary:Color= Color(0xFF680010),
    primaryContainer:Color= Color(0xFF93001B),
    onPrimaryContainer:Color= Color(0xFFFFDAD8),
    secondary:Color= Color(0xFFE6BDBB),
    onSecondary:Color= Color(0xFF442928),
    secondaryContainer:Color= Color(0xFF5D3F3E),
    onSecondaryContainer:Color= Color(0xFFFFDAD8),
    tertiary:Color= Color(0xFFE3C28C),
    onTertiary:Color= Color(0xFF412D05),
    tertiaryContainer:Color= Color(0xFF5A4319),
    onTertiaryContainer:Color= Color(0xFFFFDEAB),
    error:Color= Color(0xFFFFB4AB),
    errorContainer:Color= Color(0xFF93000A),
    onError:Color= Color(0xFF690005),
    onErrorContainer:Color= Color(0xFFFFDAD6),
    background:Color= Color(0xFF201A1A),
    onBackground:Color= Color(0xFFEDE0DE),
    surface:Color= Color(0xFF201A1A),
    onSurface:Color= Color(0xFFEDE0DE),
    surfaceVariant:Color= Color(0xFF524342),
    onSurfaceVariant:Color= Color(0xFFD7C1C0),
    outline:Color= Color(0xFFA08C8B),
    inverseOnSurface:Color= Color(0xFF201A1A),
    inverseSurface:Color= Color(0xFFEDE0DE),
    inversePrimary:Color= Color(0xFFBF0026),
    shadow:Color= Color(0xFF000000),
    surfaceTint:Color= Color(0xFFFFB3B0),
    outlineVariant:Color= Color(0xFF524342),
    scrim:Color= Color(0xFF000000)
) =
    ColorScheme(
        primary = primary,
        onPrimary = onPrimary,
        primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer,
        inversePrimary = inversePrimary,
        secondary = secondary,
        onSecondary = onSecondary,
        secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer,
        tertiary = tertiary,
        onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer,
        onTertiaryContainer = onTertiaryContainer,
        background = background,
        onBackground = onBackground,
        surface = surface,
        onSurface = onSurface,
        surfaceVariant = surfaceVariant,
        onSurfaceVariant = onSurfaceVariant,
        surfaceTint = surfaceTint,
        inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface,
        error = error,
        onError = onError,
        errorContainer = errorContainer,
        onErrorContainer = onErrorContainer,
        outline = outline,
        outlineVariant = outlineVariant,
        scrim = scrim,
        surfaceBright = surface,
        surfaceContainer = secondaryContainer,
        surfaceContainerHigh = secondaryContainer,
        surfaceContainerHighest = surface,
        surfaceContainerLow = surface,
        surfaceContainerLowest = surface,
        surfaceDim = surfaceVariant,
    )


